### ISSUE TITLE
How to hard code the port in integration tests in Grails 3.1.19

### ISSUE THREAD

**Issue by sdelamo** [grails/grails-core#10039]
From Grails 3.1.9 relase notes:

`Integration Test Port Integration and functional tests now run on a random port instead of the same port as the application by default. This is to avoid port conflict problems when the application is already running. Integration tests that hard code the port will need to be altered to use the serverPort property of tests marked with @Integration`

In particular I am asking about this part:

> Integration tests that hard code the port will need to be altered to use the serverPort property of tests marked with @Integration`

I don't understand exactly how to use the serverPort which is mentioned.

I've tried editing application.yml

```
environments:
    development:
        dataSource:
            dbCreate: create-drop
            url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    test:
        server: 
            port: 8090
        grails:
            serverUrl: http://localhost:8090
```
or 

```
environments:
    development:
        dataSource:
            dbCreate: create-drop
            url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    test:
        grails:
            serverUrl: http://localhost:8090
            serverPort: 8090
```

or 

```
environments:
    development:
        dataSource:
            dbCreate: create-drop
            url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    test:
        grails:
            serverUrl: http://localhost:8090
            server:
                port: 8090
```

### Steps to Reproduce

- Create a new grails app with 3.1.19

- Create an integration test with the source mentioned in the Expected behaviour block of this issue.

- Modify the application.yml file in any of the described ways.

### Expected Behaviour

I expect this test to pass:

```
import grails.test.mixin.integration.Integration
import grails.transaction.*
import spock.lang.*
import org.springframework.beans.factory.annotation.Value

@Integration
@Rollback
class TestControllerSpec extends Specification {

    @Value('${local.server.port}')
    Integer serverPort

    void "test server port is not random"() {
        expect: 
        serverPort == 8090
    }
}
```

### Actual Behaviour

grails test-app -integration fails

### Environment Information

- **Operating System**: OSX El Capitan
- **Grails Version:** 3.1.9
- **JDK Version:** 1.8.0_45
