### ISSUE TITLE
Domain class in grails 3 does not create the table if other datasource than default is used

### ISSUE THREAD

**Issue by frangarcia** [grails/grails-core#10069]
I have realised of a different behaviour from grails 2.5.0 and grails 3.1.8. 

I have pushed 2 different repositories to represent the problem:

Grails 2.5.0: https://github.com/frangarcia/grails2gorm
Grails 3.1.8: https://github.com/frangarcia/grails3gorm

Both projects only have a domain class called Content.groovy which does not use the default datasource but another one called master (check DataSource.groovy in grails 2 project and application.yml in Grails 3 project).

After starting up the projects and going to 
http://localhost:8080/gorm2error/dbconsole in Grails 2 and http://localhost:8080/dbconsole in Grails 3) and connect to the master database (please check details at config files)

Connecting to **Grails 2** project database

https://puu.sh/qgkMZ/da12b03c79.png

Checking tables in **Grails 2** project database

https://puu.sh/qgkPg/5a350a83d3.png

The CONTENT table is in place with all the necessary fields.

BUT

Connecting to **Grails 3** project database

https://puu.sh/qgkUA/e5fe13d277.png

Checking tables in **Grails 3** project database

https://puu.sh/qgkW2/805e4c68ba.png

in this case, I have also checked the table is not even in the default database

https://puu.sh/qgl5e/220749cf03.png

- **Operating System**: Mac OS X - 10.11.6
- **Grails Version:** 3.1.8
- **JDK Version:** 1.8.0_91

**UPDATE**: just checked also the problem is still in grails 3.1.9

**Comment by graemerocher** [comment]
Note this is fixed in GORM 6 and 3.2 M2

**Comment by frangarcia** [comment]
I have just tried with Grails 3.2 M2 and it does not seem to be working. It does not even start up the application: https://github.com/frangarcia/grails32gorm

It throws the exception: 

Caused by: org.grails.datastore.mapping.core.exceptions.ConfigurationException: DataSource not found for name [master] in configuration. Please check your multiple data sources configuration and try again.

**Comment by graemerocher** [comment]
That is because your configuration is wrong, in Grails 3+ data sources are configured under `dataSources` key, not using a suffix like `dataSource_blah`. See https://github.com/grails/gorm-hibernate5/blob/master/examples/grails31-multiple-datasources/grails-app/conf/application.yml#L72

For an example

**Comment by graemerocher** [comment]
Your configuration being wrong is also probably contributing to your issues with Grails 3 + GORM 5

**Comment by frangarcia** [comment]
I have changed my project with Grails 3.1.9 to this:

`environments:
    development:
        dataSources:
            dataSource:
                dbCreate: create-drop
                url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
            master:
                dbCreate: create-drop
                url: jdbc:h2:mem:devDb2;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE`

and right now, the content table is created in the default datasource, but it should be created in the master one.

**Comment by frangarcia** [comment]
I have changed my application.yml to this:

`environments:

    development:

        dataSources:

            dataSource:

                dbCreate: create-drop

                url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE

            master:

                dbCreate: create-drop

                url: jdbc:h2:mem:devDb2;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE`

and right now, instead of creating the table in the master dataSource, it is being created in the default one.

**Comment by graemerocher** [comment]
Can't reproduce this personally, I modified your example with the configuration:

```
dataSources:
    dataSource:
        pooled: true
        jmxExport: true
        driverClassName: org.h2.Driver
        username: sa
        password:
        dbCreate: create-drop
        url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE

    master:
        pooled: true
        jmxExport: true
        driverClassName: org.h2.Driver
        username: sa
        password:
        dbCreate: create-drop
        url: jdbc:h2:mem:masterDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
```

And it creates the `content` table in the `masterDb` as expected
