### ISSUE TITLE
Grails YAML loader is not handling configurations with lists of maps and property source resolution

### ISSUE THREAD

**Issue by olliefreeman** [grails/grails-core#10340]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Use the https://github.com/olliefreeman/grails-rabbitmq-native (grails-3.x branch) plugin as this is where I have encountered list of maps
2. Use the config as it is in the rabbitmq-native-test application.
3. Run the tests
4. The plugin attempts to connect to `${rabbitmq.host}:${rabbitmq.port}`

### Expected Behaviour

The spring property values should be resolved to the values provided in the rest of the config.

### Actual Behaviour

The values are not resolved.
Investigation shows this is because when `grailsApplication.config.rabbitmq.connections[0]` is called it returns a `org.springframework.beans.factory.config.YamlProcessor.StrictMapAppenderConstructor` rather than a `org.grails.config.NavigableMap`

### Environment Information

- **Operating System**: Any
- **Grails Version:** 3.1.x
- **JDK Version:** 7 & 8

### Example Application

If you edit the rabbitmq-native-test application in the repo and set the `application.yml` to hold

```
rabbitmq:
    host: localhost
    port: 5672
    user: guest
    password: guest
    connections:
      - name: connection1
        host: localhost
        username: guest
        password: guest
        virtualHost: test1.rabbitmq.budjb.com
        isDefault: true

      - name: connection2
        host: ${rabbitmq.host}
        port: ${rabbitmq.port}
        username: ${rabbitmq.user}
        password: ${rabbitmq.password}
        virtualHost: test2.rabbitmq.budjb.com
```
you can replicate this issue

**Comment by jameskleeh** [comment]
I can't reproduce this. I put a breakpoint here and the data was normal. https://github.com/budjb/grails-rabbitmq-native/blob/72b6c11c0d7e613a1fc71c16dc8a33f7a0a832d2/rabbitmq-native/src/main/groovy/com/budjb/rabbitmq/connection/ConnectionManagerImpl.groovy#L148

Provide an example application with precise steps to reproduce the issue

**Comment by jameskleeh** [comment]
Are you attempting to have `${}` resolve to previous parts of the configuration? If so, it is designed to resolve from environment variables, not look at previous config.

**Comment by olliefreeman** [comment]
I'm building several tests to demonstrate the issues. And have changed the link to my forked repo instead of the original repo.

I have actually managed to work out there seems to be 2 issues here rather than 1.

In my main repo I have a grails application web server which has multiple grails plugins which perform actual work. Some of these plugins use the rabbitmq plugin, and as such provide some basic config in plugin.yml for exchanges, queues and connections they expect to exist.

The main application then provides some more (along with duplicating at least the connection config), 

* the first issue I have found is that when the plugin.yml config is merged the elements which are duplicated are not being resolved back to maps but being kept as `org.springframework.beans.factory.config.YamlProcessor.StrictMapAppenderConstructor` and the resulting entry in the config is actually a `Set` not `ArrayList`, which is what it is in the event there is no duplication. I have tried to replicate this in the repo by using a secondary plugin with a yml file, however as you can see from the `com.budjb.rabbitmq.test.ConfigurationSpec` file is it currently failing as for some unknown reason (and this works fine in my main repo, but not here) the merge of property sources is actually overwriting the list of queues and we are losing the one which is only defined in the plugin.yml file (line 38: `topic-queue-sub-exchange-unused`)

* the second issue is to do with the resolution of `${}` properties. You can now see this in action in the `application.yml` file in the rabbitmq-native-test application. I have written a hack to resolve these values for now. However whilst you claim this is only supposed to work from environment variables, it actually does work in normal situations as well. In my main repo I have the application.yml file in the main application provide connection details for databases and previously for the rabbit system, and all the plugin.yml files provide the individual dataSources all of which use config like the below. And it all resolves fine, therefore if this is not intended, then please don't remove it as it is very very useful. Either way, once working with lists of maps this resolution does not work. If you comment out the contents of `com.budjb.rabbitmq.utils.ConfigPropertyResolver.fixPropertyResolution` then you will see this failing.

```
#application.yml
database:
    host: localhost
    port: 5432
    user: admin
    password: password
    auditing.name: audit
    test.name: testing_database
    common.name: common
rabbitmq:
    host: localhost
    port: 5672
    user: guest
    password: guest
---
```

```
plugin.yml
---
dataSources:
    testing_datasource:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        jmxExport: true
        url: jdbc:postgresql://${database.host}:${database.port}/${database.test.name}
        driverClassName: org.postgresql.Driver
        username: ${database.user}
        password: ${database.password}
        #dbCreate: create-drop
        formatSql: true
---
rabbitmq:
    connections:
        - host: ${rabbitmq.host}
          port: ${rabbitmq.port}
          username: ${rabbitmq.user}
          password: ${rabbitmq.password}
          isDefault: true
          name: default

```
