### ISSUE TITLE
Circular dependency in spring beans when using at least 3 datasources

### ISSUE THREAD

**Issue by gubespam** [grails/grails-core#10396]
### Steps to reproduce:
1. Create a new Grails application
2. Add configuration in application.yml for a second and third datasource (total of 3 datasources)
3. Change the logging level for spring bean to WARN. Add the following to logback.groovy:
`logger 'org.springframework.beans', WARN`
3. `grails run-app`

You will receive warnings like the following:
> WARN  [org.springframework.beans.factory.support.DefaultListableBeanFactory] (main) Bean creation exception on non-lazy FactoryBean type check: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hibernateDatastore_tertiary': Cannot resolve reference to bean 'hibernateDatastore' while setting bean property 'targetObject'; nested exception is org.springframework.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'hibernateDatastore': Requested bean is currently in creation: Is there an unresolvable circular reference?

Happens both when running `grails run-app` and as a standalone war file.

### Environment Information

- **Grails Version**: Reproducible with 3.2.2 and 3.2.4
- **JDK Version:** 8.0

### Example Application

[multidatasource.zip](https://github.com/grails/grails-core/files/700559/multidatasource.zip)

**Comment by gubespam** [comment]
Here is the relevant part of the application.yml config (also in the attached application zip file).

```
dataSources:
    dataSource:
        pooled: true
        jmxExport: true
        driverClassName: org.h2.Driver
        username: sa
        password:
    secondary:
        pooled: true
        jmxExport: true
        driverClassName: org.h2.Driver
        username: sa
        password:
    tertiary:
        pooled: true
        jmxExport: true
        driverClassName: org.h2.Driver
        username: sa
        password:

environments:
    development:
        dataSources:
            dataSource:
                dbCreate: create-drop
                url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
            secondary:
                dbCreate: create-drop
                url: jdbc:h2:mem:devDbSecondary;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
            tertiary:
                dbCreate: create-drop
                url: jdbc:h2:mem:devDbTertiary;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
```
