### ISSUE TITLE
Grails 3.2.8 war created for custom environment always runs under development environment.

### ISSUE THREAD

**Issue by HardikModha** [grails/grails-core#10569]
### Task List

- [x] Steps to reproduce provided
- ~~[ ] Stacktrace (if present) provided~~
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Use Grails version 3.2.7 or greater (Currently 3.2.8) to create a sample test application and create a war for any custom environment. 
e.g. Creating war with staging environment. `grails -Dgrails.env=staging war`
2. Now deploy war file on server (e.g. Tomcat) or use `java -jar Test.war`  to run the war using embedded tomcat container.
3. Although we created the war using staging environment, application will run in the development environment.

### Expected Behaviour

Custom environment specific war should be created and while running the application, it should run in the environment it was created for.

### Actual Behaviour

Application always runs in the development environment.
### Environment Information

- **Operating System**: Ubuntu 14.04
- **Grails Version:** 3.2.7 and 3.2.8
- **JDK Version:** 1.8.0_111

### Example Application
GitHub repo to reproduce this issue: [grails-test](https://github.com/HardikModha/grails-test)

[#10546](https://github.com/grails/grails-core/issues/10546) is relevant and claims to have fixed the issue but that solution only fixes the environment name printed after the war is created.
` Built application to build/libs using environment: staging` <---- It fixes only this display environment name.

**PS**: I used the same configuration, followed the same steps using grails v3.2.6 and got the expected/correct results.

**Comment by jameskleeh** [comment]
This commit fixed the issue in my testing https://github.com/grails/grails-core/commit/d780175f3680969596b429819857565c310b8e21

**Comment by HardikModha** [comment]
@jameskleeh But seems like that only fixes the environment displayed in the message.
`Built application to build/libs using environment: staging` <--- This environment name.

I tried creating war with the custom environment using version 3.2.8 and it didn't work. Application was running in the development environment. It can be reproduced easily.

**Comment by jameskleeh** [comment]
@HardikModha No, that is a different commit, https://github.com/grails-profiles/base/commit/1f1ea0989d6222f39a20322d5c6d15f037667abb

**Comment by HardikModha** [comment]
@jameskleeh doesn't fix the issue.

**Comment by jameskleeh** [comment]
I can't reproduce the issue. Steps I took:

1. `grails create-app test-war` (Grails 3.2.8)
2. Add staging database configuration:
```
    staging:
        dataSource:
            dbCreate: create-drop
            url: jdbc:h2:./stagingDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
```
3. Add a domain class (`grails create-domain-class Test`)
4. Save the domain class in Bootstrap `new Test().save()`
5. Build war with `grails -Dgrails.env=staging war`
6. Deploy to Tomcat 8.5.13
7. Verify `stagingDb.mv.db` exists in the tomcat root directory
