### ISSUE TITLE
global gorm.autowire does not work in Grails 3.3.0.M2

### ISSUE THREAD

**Issue by sdelamo** [grails/grails-core#10679]
Given the domain class: 

```
package demo

import groovy.transform.CompileStatic

@CompileStatic
class Person {
    PersonService personService
    String name

    static transients = ['personService']

    String hi() {
        personService.sayHello(name)
    }
}
```

and the service: 

```
package demo

import groovy.transform.CompileStatic

@CompileStatic
class PersonService {

    String sayHello(String name) {
        "Mr $name"
    }
}
```

With `gorm.autowired` turn on in `application.yml`

```
---
grails:
    gorm:
        # Whether to autowire entities. 
        # Disabled by default for performance reasons.
        autowire: true
```

and the next integration Test
```
package demo

import grails.test.mixin.integration.Integration
import spock.lang.Specification

@Integration
class PersonIntegrationSpec extends Specification {

    def "service is injected"() {
        when:
        def person = new Person(name: 'Sergio')
        def text = person.hi()

        then:
        noExceptionThrown()
        text == 'Mr Sergio'
    }
}
```

# Current Behaviour 

In Grails 3.2.10 it passes

In Grails 3.3.0.M2 it fails.

In Grails 3.3.0.M2, the tests passes if I turn the global autowire off and set the autowire at domain class level as documented in [Domain Autowire Disabled by Default](http://gorm.grails.org/latest/hibernate/manual/index.html#_domain_autowiring_disabled_by_default)

```
---
grails:
    gorm:
        autowire: false
```

```
package demo

class Person {
    PersonService personService
    String name

    static transients = ['personService']

    String hi() {
        personService.sayHello(name)
    }

    static mapping = {
        autowire true
    }
}

```

# Expected behaviour

I will expect the global autowire true to work 

# Example Repository

https://github.com/grails-core-issues-forks/github-issue-10679
