### ISSUE TITLE
Grails Environment Aware  - Spring Boot configuration property 

### ISSUE THREAD

**Issue by sdelamo** [grails/grails-core#10807]
## Steps to reproduce 

````
$ pwd
/Users/sdelamo/Developer/tests/
$ mkdir loggingconfig
$ cd loggingconfig
$ grails create-app demo --inplace
$ mkdir dev
$ cp grails-app/conf/logback.groovy  dev/logback.groovy 
$ mkdir prod
$ cp grails-app/conf/logback.groovy  prod/logback.groovy 
$ mkdir test
$ cp grails-app/conf/logback.groovy  test/logback.groovy 
````

Modify `grails-app/conf/application.yml` and set the location of the config file using the "logging.config" property of Spring Boot. 

````
---
environments:
    development:
        logging:
            config: /Users/sdelamo/Developer/tests/loggingconfig/dev/logback.groovy 
    test:
        logging:
            config: /Users/sdelamo/Developer/tests/loggingconfig/test/logback.groovy 
    production:
        logging:
            config: /Users/sdelamo/Developer/tests/loggingconfig/prod/logback.groovy 
````

Modify  `grails-app/init/demo/BootStrap.groovy`

````
package demo

class BootStrap {

    def grailsApplication

    def init = { servletContext ->
        println grailsApplication.config.getProperty('logging.config')
    }
    def destroy = {
    }
}
````

If you run `grails test run-app`, I expected to see: 

````
/Users/sdelamo/Developer/test/loggingconfig/test/logback.groovy
Grails application running at http://localhost:8080 in environment: test
````

However I get: 

````
/Users/sdelamo/Developer/test/loggingconfig/dev/logback.groovy
Grails application running at http://localhost:8080 in environment: test
````

There is a workaround possible. 

I can remove the environment aware configuration block from `grails-app/conf/application.yml` and create a configuration file per environment: 

create `grails-app/conf/application-development.yml` with content:

````
logging:
    config: /Users/sdelamo/Developer/tests/loggingconfig/dev/logback.groovy 
````

create `grails-app/conf/application-test.yml` with content:

````
logging:
    config: /Users/sdelamo/Developer/tests/loggingconfig/test/logback.groovy 
````

create `grails-app/conf/application-prod.yml` with content:

````
logging:
    config: /Users/sdelamo/Developer/tests/loggingconfig/prod/logback.groovy 
````

then if I you run `grails test run-app`, I expected to see: 

````
/Users/sdelamo/Developer/test/loggingconfig/test/logback.groovy
Grails application running at http://localhost:8080 in environment: test
````

**Grails Version**: 3.3.0
**OS Version**: MacOS
