### ISSUE TITLE
ChainedTransactionManagerPostProcessor config docs inconsistency

### ISSUE THREAD

**Issue by zyro23** [grails/grails-core#10823]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

ref. http://docs.grails.org/latest/guide/upgrading.html

while the upgrade docs suggest that the correct config for re-enabling the `ChainedTransactionManagerPostProcessor` is this:

```yml
grails:
  transaction:
    chainedTransactionManagerPostProcessor:
      enabled: true
      blacklistPattern: '.*'
```

the source looks like it checks `grails.transaction.chainedTransactionManager.enabled` (https://github.com/grails/grails-core/blob/v3.3.1/grails-plugin-datasource/src/main/groovy/org/grails/plugins/datasource/DataSourceGrailsPlugin.groovy#L54).

also, `blacklistPattern: '.*'` means excluding all candidates, doesnt it?

so i think it should be:

```yml
grails:
  transaction:
    chainedTransactionManager:
      enabled: true
```

debugging into the `DataSourceGrailsPlugin` confirmed that.

### Expected Behaviour

n/a

### Actual Behaviour

n/a

### Environment Information

- **Operating System**: win x64
- **Grails Version:** 3.3.1
- **JDK Version:** oracle 8u131
- **Container Version (If Applicable):** n/a

### Example Application

- TODO: link to github repository with example that reproduces the issue
