### ISSUE TITLE
Cannot use HikariCP connection pool dataSource when deployed under Tomcat application server

### ISSUE THREAD

**Issue by davidbairdala** [grails/grails-core#10943]
I am trying to use the HikariCP DataSource for connection pooling. I have configured a dataSource in application.yml (pooled: true) and I have removed the dependency on tomcat-jdbc.jar from build.gradle.

When I run my application using "grails run-app" or deploy the generated war file under a different container (such as Jetty) the HikariCP dataSource is used, and pooling works as expected.

When I deploy the generated war file under a full installation of Tomcat8, the dataSource is always the tomcat connection pool.

I believe this is happening because the tomcat-jdbc.jar is always going to be present under a full installation of Tomcat, and the way that the DataSourceBuilder searches for a list of predefined DataSource implementations means that org.apache.tomcat.jdbc.pool.DataSource will always be selected as the DataSource implementation. I notice that the DataSourceBuilder can allow the type to use to be explicitly set (via the type() method), but I cannot see how to set the type via Grails configuration.

Would it be possible to add another configuration option under dataSource (dataSourceImpl or dataSourceType?) that would allow me to explicitly name the dataSource type?

### Task List

- [ x ] Steps to reproduce provided
- [ n/a ] Stacktrace (if present) provided
- [ x ] Example that reproduces the problem uploaded to Github
- [ x ] Full description of the issue provided (see below)

### Steps to Reproduce
1. Clone the sample application from the GitHub link below
2. Change directory to ./connection-pool-test
2. Execute command 'grails run-app' and browse to http://localhost:8080
3. Observe that the type of the configured DataSource is 'com.zaxxer.hikari.HikariDataSource' and the maximumPoolSize matches that the number configured in application.yml
4. Execute command 'gradle assemble'
5. Deploy the generated war file (build/lib/connection-pool-test-0.1.war) under a complete installation of Tomcat 8
6. Browse to where the application was deployed (e.g. http://localhost:8080/connection-pool-test-0.1)

### Expected Behaviour
I expect that the message displayed on the version deployed under tomcat should match the message when run under 'grails run-app' (i.e. Datasource is HikariDataSource)

### Actual Behaviour
The configured DataSource is actually a 'org.apache.tomcat.jdbc.pool.DataSource'

### Environment Information

- **Operating System**: Ubuntu 17.10
- **Grails Version:** 3.3.2
- **JDK Version:** openjdk version "1.8.0_151"
- **Container Version (If Applicable):** Tomcat8 (8.5.21, install via 'apt install tomcat8')

### Example Application

- https://github.com/davidbairdala/connection-pool-test.git

**Comment by gmore** [comment]
Did you try to add a Jndi datasource in application.yml ?

**Comment by ilopmar** [comment]
I've sent this PR https://github.com/grails/grails-data-mapping/pull/1168 that allows defining the database pool class. Once this is merged you could be able to define the `type` in `application.yml`:
```
---
hibernate:
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false
dataSource:
    pooled: true
    jmxExport: true
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    type: com.zaxxer.hikari.HikariDataSource # <--- HikariDataSource class
    properties:
      maximumPoolSize: 20
```

With the previous configuration and GORM version `6.1.11.BUILD-SNAPSHOT` the application uses Hikari pool when deployed in tomcat.

Additionally, as a workaround you can remove the library `tomcat-jdbc.jar` from `$TOMCAT_HOME/lib`, although I'm not sure if doing that will break anything inside tomcat.
