### ISSUE TITLE
Grails 4: spring-dev-tools reloads app when not nessisarry.

### ISSUE THREAD

**Issue by erichelgeson** [grails/grails-core#11225]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Edit a `.gsp` or `.gson` file
or
1. Edit any file under `grails-app/assets`
or
1. Run `./gradlew test` 
or
1. Edit `logback.groovy`

### Expected Behaviour

spring-dev-tools will not reload context

### Actual Behaviour

spring-dev-tools reloads app unnecessarily.

We should ensure Grails spring-dev-tools default excludes are tuned for Grails files that do not require reload (gsp/gson) or are not considered in the reloaded context (logback). There may be others that I've not tested (internationalization, etc) 

Another consideration is plugins may want to participate/add files that are not required for reload?

### Environment Information

- **Operating System**: MacOSX
- **Grails Version:** Grails 4 (master 744324eda1e42cfa95b2801c84c94d718b85840f)
- **JDK Version:** 11.0.1 zulu
- **Container Version (If Applicable):** n/a

**Comment by graemerocher** [comment]
Seems this is just a matter of configuration

```yaml
spring:
    devtools:
        restart:
            exclude:
                - grails-app/views/**
                - grails-app/i18n/**
                - grails-app/conf/**
```
