### ISSUE TITLE
Grails 4M1 - spring-dev-tools excludes syntax incorrect 

### ISSUE THREAD

**Issue by erichelgeson** [grails/grails-core#11249]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

Make a change to a gps

### Expected Behaviour

App does not restart

### Actual Behaviour

App restarts.

Syntax should be changed to:

```yml
---
spring:
    devtools:
        restart:
            exclude: grails-app/views/**,grails-app/i18n/**,grails-app/conf/**
```

### Environment Information

- **Operating System**: Mac 10.14.3
- **Grails Version:** 4.0.0.M1
- **JDK Version:** OpenJDK 11.0.2
- **Container Version (If Applicable):** n/a

### Example Application

- n/a
