### ISSUE TITLE
Upgrading the mysql-connector-java to 6.x or 8.x causes initial sql table creation to partially Fail

### ISSUE THREAD

**Issue by dularion** [grails/grails-core#11319]
Hi Guys, 
not sure if this is the right place for it or not, but I cannot find any issue reports on this online for pure hibernate or the mysql-connector-java library. Maybe you guys can help. 
I have this open-source project streama, based in grails  https://github.com/streamaserver/streama and for a couple of versions now we have upgraded the mysql-connector-java library to 8.0.x. 
For pre-existing MySQL databases this didnt create an issue, but for new projects with a fresh empty MySQL database, initial startup fails with an error like `Caused by: java.sql.SQLSyntaxErrorException: Table 'streama.settings' doesn't exist` or the same for the table `role`.

Here is an example stacktrace: https://pastebin.com/qUv0mFct

Note: even downgrading to the connector version 6.x wont help. Only downgrading to 5.1.x fixes the issue permanently. 

### Steps to Reproduce

1. download a copy of https://github.com/streamaserver/streama/releases/tag/v1.6.7
2. in an application.yml alongside the .jar, add the following settings: 
```yml
environments:
    production:
        dataSource:
            driverClassName:  'com.mysql.cj.jdbc.Driver'
            url: "jdbc:mysql://localhost/streama?useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false"
            username: root
            password: ''
```
3. create a database called `streama` in a mysql installation with username and password as u see fit (just adjust in the application.yml as well) 
4. execute (on linux, you can just execute the .jar as an executable file) 

### Expected Behaviour
Should create all tables that are part of the domain directory in the grails-app (see https://github.com/streamaserver/streama/tree/master/grails-app/domain/streama)

### Actual Behaviour
fails with stacktrace https://pastebin.com/qUv0mFct

### Environment Information

- **Operating System**: Ubuntu 18.04
- **Grails Version:** 3.2.6
- **JDK Version:** 1.8.0_191

### Example Application
https://github.com/streamaserver/streama/releases/tag/v1.6.7

### Temporary fix
If I downgrade the mysql-connector to 5.1.47 and change the driverClass to `'com.mysql.jdbc.Driver'` (removing the cj. part required from 6.x onwards) everything works fine. 

I hope you guys can help!
