### ISSUE TITLE
Old mysql connections dont get killed on application reload

### ISSUE THREAD

**Issue by luiszimmermann** [grails/grails-core#11341]
### Steps to Reproduce

1. Create a New App
    *  `grails create-app testmysql`
2. Add mysql dependencies in `build.gradle`
    *  `runtime "mysql:mysql-connector-java:5.1.47"`
3. Create Schema and add connection to mysql in `application.yml`
```
dataSource:
            dbCreate: "update"
            #logSql: true
            url: "jdbc:mysql://localhost/testmysql?useSSL=false&allowPublicKeyRetrieval=true"
            driverClassName: "com.mysql.jdbc.Driver"
            username: "user"
            password: "pass"
```

### Expected Behaviour

When a file gets changed and Grails 4 reload, the old connections should be gone.

### Actual Behaviour

When a file gets changed and grails reaload, the old connections stay alive. With time, and many reloads, the mysql will reach the limit.

### Environment Information

- **Operating System**: `Windows 10`
- **Grails Version:** `Grails 4.0.0.RC2`
- **JDK Version:** 
```
openjdk version "1.8.0_212"
OpenJDK Runtime Environment Corretto-8.212.04.2 (build 1.8.0_212-b04)
OpenJDK 64-Bit Server VM Corretto-8.212.04.2 (build 25.212-b04, mixed mode)
```
- **MySQL:** 8.0.13
