### ISSUE TITLE
Grails4 Could not find matching constructor for InterceptedUrl

### ISSUE THREAD

**Issue by kszymko** [grails/grails-core#11384]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. generate the simple app:
```
    grails create-app helloworld4
```
2. in build.gradle add dependencies:
```
dependencies {
    ...
    compile 'org.grails.plugins:spring-security-core:4.0.0.RC2'
    compile 'org.springframework.security:spring-security-core:5.1.5.RELEASE'
}
```
3. in application.yml add:

```
grails:
    plugin:
        springsecurity:
            # Whether the plugin is enabled
            active: true
            interceptUrlMap:
                - { pattern: '/assets/**',               access: ['permitAll'] }
                - { pattern: '/css/**',                  access: ['permitAll'] }
                - { pattern: '/images/**',               access: ['permitAll'] }
            securityConfigType: 'InterceptUrlMap'
```
4. gradle clean bootRun

### Expected Behaviour

Application should start without any problems.

### Actual Behaviour

Exception is thrown:

groovy.lang.GroovyRuntimeException: Could not find matching constructor for: grails.plugin.springsecurity.InterceptedUrl(String, ArrayList, org.grails.config.NavigableMap$NullSafeNavigator)

### Environment Information

- **Operating System**:  Win 10
- **Grails Version:** 4.0.0
- **JDK Version:** 1.8.0_221
- **Container Version (If Applicable):** N/A

### Example Application

- N/A
