### ISSUE TITLE
Grails 4: stop-app not working in interactive mode

### ISSUE THREAD

**Issue by zbubric** [grails/grails-core#11398]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create new grails 4 app
2. Enter interactive console
3. Use run-app script to start app
4. Try to use stop-app script

### Expected Behaviour

1. Application should be stopped (not accessible)
2. bootrstrap.groovy::destroy sequence should be invoked
3. (optional) if dbCreate is set to create-drop, db schema tables should be dropped

### Actual Behaviour

1. Application still running
2. bootrstrap.groovy::destroy sequence not invoked
3. (optional) with dbCreate set to create-drop, db schema tables are not dropped
4. Missleading console output stating that bootRunn not running.

### Environment Information

- **Operating System**: Win 10-64
- **Grails Version:** 4.0.0
- **JDK Version:** 1.8

### Console output
| Starting interactive mode...
| Enter a command name to run. Use TAB for completion:
grails> run-app
| Running application...
Hello from bootstrap
Grails application running at http://localhost:8080 in environment: development
<=======<==========---> 83% EXECUTING [29s]
> :bootR> :bootRun
grails> stop-app
<==========---> 83% EXECUTING [46s]tempting remote shutdown.
<=======<==========---> 83% EXECUTING [1m 9s]
> :bootR> :bootRunn not running.

### Example Application
N/A

**Comment by olliefreeman** [comment]
I just raised this in a the profile

https://github.com/grails-profiles/base/issues/31

Its the reason why the shutdown is not working, JMX is failing so its attempting to use the API shutdown, which needs to be activated in the config....I can't remember how

**Comment by olliefreeman** [comment]
@zbubric 

alter application.yml at the `management` point to be 

```
management:
    endpoints:
        enabled-by-default: false
        web:
            exposure:
                include:
                    - 'health'
                    - 'shutdown'
    endpoint:
        shutdown:
            enabled: true
        health:
            enabled: true
```

this will enable the shutdown endpoint however there still seems to be an issue actually stopping the application. I also can't get ctrl+c to work when doing `grails run-app` outside of interactive mode
