### ISSUE TITLE
Using multiple dataSources in applications.yml cause a strange behavior

### ISSUE THREAD

**Issue by humberthardy** [grails/grails-core#11425]
When we switch from 

```
dataSource:
    driverClassName: org.h2.Driver
    properties:
        testOnBorrow: true
```

to

```
dataSources:
    dataSource:
        driverClassName: org.h2.Driver
        properties:
            testOnBorrow: true
```

It seems that we have weird behavior: the `dataSource` bean uses a connection which ignores `testOnBorrow`

#### Wrong behavior

1. Run the application
2. Go the endpoint http://localhost:8080 and figure that the bean named `dataSource` is using a connection from a pool with 'testOnBorrow' set to false

#### Good behavior
1. Comment `dataSources` section and uncomment `dataSource` section in `application.yml`
2. Go the endpoint http://localhost:8080 and figure that the dataSource bean is using a connection with 'testOnBorrow' set to `true`. The Pool object from `sessionFactory` and `dataSource` seems to be the same

### Expected Behaviour

`dataSource` bean should use connections created by hibernate and respect the properties provided by the application.yml 
When we use the single dataSource notations (without `dataSources` section) everything is working as expected.

### Actual Behaviour
When the bean `dataSource` is created, a new Tomcat ConnectionPool is created (instead of recycling the hibernate one) and the `properties:` section is ignored.

### Environment Information

- **Operating System**: Linux
- **Grails Version:** 4.0.1
- **JDK Version:** 1.8

### Example Application

[grails4.zip](https://github.com/grails/grails-core/files/3769200/grails4.zip)
