### ISSUE TITLE
Second level cache for Domains NOT working as in Grails 3

### ISSUE THREAD

**Issue by kszymko** [grails/grails-core#11434]
# Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. grails create-app SandboxGrails4DomainCache

Add in build.gradle

```
    compile 'net.sf.ehcache:ehcache:2.10.6'
    compile 'org.hibernate:hibernate-ehcache:5.4.0.Final'

```
2. create Domain Book with enabled cache

```
class Book {
    static mapping = {
        cache true
    }
    String title
    String author
    Date releaseDate
    Integer pages
}
```

3. create Integration Test BookCacheSpec
4. configure hibernate to use second level cache and enable statistics

```
hibernate:
    generate_statistics: true
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: false
        provider_class: net.sf.ehcache.hibernate.EhCacheProvider
        region:
            factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
        region_prefix: hibernate
```

### Expected Behaviour

Region names should NOT be empty when running BookCacheSpec.

```
Statistics stats = sessionFactory.statistics
info 'secondLevelCacheRegionNames size: {}', stats.secondLevelCacheRegionNames.size()
info 'secondLevelCacheRegionNames: {}', stats.secondLevelCacheRegionNames*.toString()

```

Based on mapping block (cache true) Grails3 logged as below (it is missing in Grails4 logs:

```
[TRACE] org.hibernate.internal.SessionFactoryImpl - Building shared cache region for entity data [com.sample.Book]
[WARN ] org.hibernate.cache.ehcache.AbstractEhcacheRegionFactory - HHH020003: Could not find a specific ehcache configuration for cache named [hibernate.com.sample.Book]; using defaults.

```
If the setup changed for Grails4 please let me know what should be changed to get 
2nd level cache working for Domains. Thank you.

### Actual Behaviour

Region names is empty.

### Environment Information

- **Operating System**: Win 10
- **Grails Version:** 4.0.0
- **JDK Version:** 1.8
- **Container Version (If Applicable):** Tomcat 9.0.21
