### ISSUE TITLE
CORS mapping doesn't work as documentation states

### ISSUE THREAD

**Issue by allnightlong** [grails/grails-core#11639]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Generate new app  at https://start.grails.org/
2. Generate simple controller `cors`  as following:
```
package grails.cors

class CorsController {

    def index() {
        render 'ok'
    }
}
```
3. Add UrlMapping.groovy entry:
`"/api/cors"(controller: 'cors')`
4. Add cors config to applicaton.yml according to doc:
http://docs.grails.org/latest/guide/theWebLayer.html#cors
```
grails:
    cors:
        enabled: true
        mappings:
            /api/**: inherit
```
5. Run the app and check cors headers for CORS headers (for example, with https://www.test-cors.org/) `http://localhost:8080/api/cors`

### Expected Behaviour

 CORS headers should be added to the response

### Actual Behaviour

 CORS headers are not added. Apparently, it's happening due to the way yml config file is parsed. 

When config value is created, all special symbols (slashes and asterisks) are ommited, so when request path is checking against config, antMatcher answers with `false` (https://github.com/spring-projects/spring-framework/blob/v5.1.18.RELEASE/spring-web/src/main/java/org/springframework/web/cors/UrlBasedCorsConfigurationSource.java#L123)
### Environment Information

- **Operating System**: windows 10
- **Grails Version:** 4.0.5
- **JDK Version:** 1.8

**Comment by puneetbehl** [comment]
Did you try the following: 
```
grails:
    cors:
        enabled: true
        mappings:
            '/api/**': inherit
```
