### ISSUE TITLE
Unable to configure CORS for multiple mappings

### ISSUE THREAD

**Issue by leadtrip** [grails/grails-core#12719]
### Expected Behavior

Adding cors mappings with lists of allowedOrigins to application.yml should result in these mappings being applied when making relevant cors requests.

### Actual Behaviour

The mappings aren't applied and access is open to all.

### Steps To Reproduce

In development environment.

With this config
```
grails:
    cors:
        enabled: true
        allowedHeaders:
            - Content-Type
        mappings:
            '[/word/googleOnly]':
                allowedOrigins:
                    - https://www.google.com
            '[/word/stackoverflowOnly]':
                allowedOrigins:
                    - https://stackoverflow.com
            '[/word/anywhere]':
                allowedOrigins:
                    - '*'
```

Make a fetch request to /word/googleOnly in the linked app from a browser's developer console e.g. 

fetch("http://localhost:10005/word/googleOnly").then(a => a.text()).then(console.log)

This should only be possible from https://www.google.com but it's possible from any domain e.g.

![grails cors from google](https://user-images.githubusercontent.com/7558059/192834934-4ee6d89c-3dc6-4e30-89d4-2bddfa5b663a.JPG)

![grails cors from grailsorg](https://user-images.githubusercontent.com/7558059/192834939-2dcbe313-e214-4741-9862-5e8500626e26.JPG)

The attached screenshot of a debugging session in GrailsCorsConfiguration highlights the issue where the code is expecting an allowedOrigins key but, depending on how many keys there are they are named allowedOrigins[0] and so on.

![GrailsCorsConfiguration](https://user-images.githubusercontent.com/7558059/192836048-cd5e32f5-165a-4b74-915a-10bd98e2dc25.jpg)

### Environment Information

Windows 10 & 11
Open JDK 8
Grails 5.2.4

### Example Application

https://github.com/leadtrip/g524cors

### Version

5.2.4
