### ISSUE TITLE
CORS mappings allowedOrigins not parsed properly

### ISSUE THREAD

**Issue by okoskine** [grails/grails-core#12821]
### Expected Behavior

Allowed origins for CORS mappings should be obeyed. E.g.
 ```
grails:
    cors:
        enabled: true
        mappings:
            '[/a/**]':
                allowedOrigins:
                    - https://a.example.com
                    - https://a.example.org
            '[/b/**]':
                allowedOrigins:
                    - https://b.example.com
                    - https://b.example.org
```

### Actual Behaviour

The `allowedOrigins` list is not found in the config (instead the list items are indexed there separately):
![image](https://user-images.githubusercontent.com/3534209/208895900-9e13e47e-bf2c-4764-8bd6-433ea061d630.png)
=> All CORS mappings use the default (*) allowedOrigins.
![image](https://user-images.githubusercontent.com/3534209/208896225-e759d5c9-af63-4f06-b0c1-de12ecef7c19.png)

### Steps To Reproduce

1. `grails create-app cors`
2. add cors mappings with allowedOrigins to application.yml

### Environment Information

- Operating System: Linux
- JDK Version: 1.8.0_352

### Example Application

https://github.com/okoskine/grails5-cors-config-issue

### Version

5.2.5
