### ISSUE TITLE
Session not found issue while using secondary datasource in grails 3.3.11

### ISSUE THREAD

**Issue by LamaBimal** [grails/grails-core#12962]
### Issue description

I am extending the datasources with read replication DB in my project. I have configured the datasources as suggested in the project documentation.

https://docs.grails.org/3.3.11/guide/single.html#multipleDatasources

Following is the configuration of my application:
```
dataSources:
  usermanagement:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://<host>:3306/<db>?useUnicode=yes&characterEncoding=UTF-8&auto-rehash=false&zeroDateTimeBehavior=convertToNull&useSSL=true
    pooled: true
    jmxExport: true
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    username: dev
    password: ********

  readReplica:
    driverClassName: com.mysql.cj.jdbc.Driver
    pooled: true
    jmxExport: true
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    transactional: true
    username: o****
    password: *********

environments:
  development:
    dataSource:
      dbCreate: none
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://<db_host>:3306/om?useUnicode=yes&characterEncoding=UTF-8&auto-rehash=false&zeroDateTimeBehavior=convertToNull&useSSL=false
      username: ********
      password: *********
    datasources:
      readReplica:
        dbCreate: none
        pooled: true
        driverClassName: com.mysql.cj.jdbc.Driver
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        url: jdbc:mysql://<db_replica_host>/processing_service?autoReconnect=true&useSSL=false
        username: *********
        password: *********
```
I have added datasources in domain level as:

```
static mapping = {
            datasources (['readReplica','DEFAULT'])
    }
```
And I am getting error while using the data source as like:
```
PhaseGroup.readReplica.list()
```
**Error: No Session Found for current thread**

Caused by: org.springframework.dao.DataAccessResourceFailureException: Could not obtain current Hibernate Session; nested exception is org.hibernate.HibernateException: No Session found for current thread
	at org.grails.orm.hibernate.GrailsHibernateTemplate.getSession(GrailsHibernateTemplate.java:337)

Please suggest for the resolution on this type of issues.

```
grailsVersion=3.3.11
gormVersion=6.1.12.RELEASE
gradleWrapperVersion=3.5
```
