### ISSUE TITLE
H2 Console Docs take 6.

### ISSUE THREAD

**Issue by tircnf** [grails/grails-core#13129]
### Expected Behavior

the /h2-console endpoint no longer works with grails 6.

Building a default grails 6 app should have this endpoint enabled.

similar to:
https://github.com/grails/grails-core/issues/11390

### Actual Behaviour

System returns 404.

### Steps To Reproduce

Build a default grails 6 web-app and visit
localhost:8080/h2-console

I think one of the upgrades to spring-boot defaults the h2-console to be disabled.

Either change the default application.yml to contain the following environment block:
```
  development:
    # enable the spring h2-console.
    spring:
      h2:
        console:
          enabled: true
```

or fix the documentation that h2-console is now disabled.

### Environment Information

windows
java 11

### Version

6.0.0
