### ISSUE TITLE
Document Snapshot Deployment

### ISSUE THREAD

**Issue by codeconsole** [grails/grails-core#13571]
Document the Requirements for Deploying to the Snapshot Repository

## Discuss 
1.  Should SNAPSHOTs continue to go to jfrog starting with 7.x?
2.  Should the SNAPSHOT process require different configuration from the deployment process?

## Goals
1.  Configure https://github.com/gpc/export to publish to Snapshot Repository
2. Configure https://github.com/grails/grails-boot
3. Fix gradle.plugin is mistakenly publishing a pom under grails-core
[org/grails/grails-core/org.grails.grails-core.gradle.plugin/](https://repo.grails.org/ui/repos/tree/General/libs-snapshots-local/org.grails.grails-core.gradle.plugin/) [Unwanted Artifact?](https://repo.grails.org/ui/repos/tree/General/libs-snapshots-local/org/grails/grails-core/org.grails.grails-core.gradle.plugin/7.0.0-SNAPSHOT/)

Working Snapshots
[grails-core](https://repo.grails.org/ui/repos/tree/General/libs-snapshots-local/org/grails/grails-core/7.0.0-SNAPSHOT) 
[grails-gradle-plugin](https://repo.grails.org/ui/repos/tree/General/libs-snapshots-local/org/grails/grails-gradle-plugin/7.0.0-SNAPSHOT)
[grails-bom](https://repo.grails.org/ui/repos/tree/General/libs-snapshots-local/org/grails/grails-bom/7.0.0-SNAPSHOT)

Not Working
[grails-gsp](https://repo.grails.org/ui/repos/tree/General/libs-snapshots-local/org/grails/grails-gsp/7.0.0-SNAPSHOT)
[neo-4j](https://repo.grails.org/ui/repos/tree/General/plugins3-snapshots-local/org/grails/plugins/neo4j)

From @matrei 

An example of a simple module, publishing snapshots, is [scaffolding](https://github.com/grails/scaffolding).
It uses the org.grails.internal.grails-plugin-publish gradle plugin from grails-gradle-plugin.

[build.gradle](https://github.com/grails/scaffolding/blob/5.0.x/build.gradle)
```gradle
plugins {
    id 'java-library'
    id 'eclipse'
    id 'idea'
    id 'org.grails.grails-plugin'
    id 'org.grails.grails-gsp'
    id 'org.grails.internal.grails-plugin-publish'
}
grailsPublish {
    userOrg = "grails"
    githubSlug = 'grails/scaffolding'
    license {
        name = 'Apache-2.0'
    }
    title = "Grails Scaffolding Plugin"
    desc = "Provides scaffolding for Grails applications"
    developers = [puneetbehl: "Puneet Behl"]
}
```

Then, in the [gradle.yml ](https://github.com/grails/scaffolding/blob/5.0.x/.github/workflows/gradle.yml) github workflow it publishes on pushevents:
```yml
publish:
    if: github.event_name == 'push'
    needs: ['build']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Publish Artifacts (repo.grails.org)
        id: publish
        uses: gradle/gradle-build-action@v3
        env:
          GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
          GRADLE_ENTERPRISE_BUILD_CACHE_NODE_USER: ${{ secrets.GRADLE_ENTERPRISE_BUILD_CACHE_NODE_USER }}
          GRADLE_ENTERPRISE_BUILD_CACHE_NODE_KEY: ${{ secrets.GRADLE_ENTERPRISE_BUILD_CACHE_NODE_KEY }}
          ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
        with:
          arguments: -Dorg.gradle.internal.publish.checksums.insecure=true publish
```

[Where is scaffolding](https://repo.grails.org/ui/repos/tree/General/libs-snapshots-local/org/grails/plugins) publishing to?
