### ISSUE TITLE
Multi-Tenant domain error: Filter [tenantId] parameter [tenantId] value not set"

### ISSUE THREAD

**Issue by wureka** [grails/grails-core#14338]
Environment:
- Grails 6.2.0 (JDK-17), Grails 5.3.3 (JDK-11)
- gorm-graphql-plugin 3.0.0

I have refered your example in [https://github.com/grails/gorm-graphql/blob/4.0.x/examples/grails-tenant-app/grails-app/domain/grails/tenant/app/User.groovy](https://github.com/grails/gorm-graphql/blob/4.0.x/examples/grails-tenant-app/grails-app/domain/grails/tenant/app/User.groovy)

My Grails app is a multi-tenant system. The relevant files are as below
application.yml (only key portion):
```

grails:
    profile: vue
    codegen:
        defaultPackage: worker.order
    gorm:
        failOnError: true
        reactor:
            events: false
        multiTenancy:
            mode: DISCRIMINATOR # SCHEMA, DATABASE, DISCRIMINATOR
            tenantResolverClass: com.workerorder.multitenancy.CurrentUserByJwtTenantResolver
```

domain TenantFunc:
```

class TenantFunc  implements MultiTenant<TenantFunc> {
    String vueComponentName
    String funcname
    int displayorder = 0
    String position
    boolean active
    String updatedBy
    String createdBy
    Date dateCreated
    Date lastUpdated

    String tenantName
    static graphql = true
    static mapping = {
        tenantId name: 'tenantName'
        active  default:'true'
    }
    
    static constraints = {
        tenantName      maxSize: FieldLen.TENANT_NAME, index:'tenant_all_func_tenant_func'
        vueComponentName    maxSize: 60, unique: ['tenantName']
        funcname            maxSize: 100, unique: ['tenantName']
        position            maxSize: 20
    }

    static graphql = true
}
```

graphql in http://localhost:8080/graphql/browser :

```
query {
  tenantFuncList {
    id
    
  }
}
```

result:
```

{
  "data": {
    "tenantFuncList": null
  },
  "errors": [
    {
      "message": "Exception while fetching data (/tenantFuncList) : Filter [tenantId] parameter [tenantId] value not set",
      "errorType": "DataFetchingException",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ]
    }
  ]
}
```

How to solve this error ? Thanks
