### ISSUE TITLE
Grails 3.0.1 dialect setting in application.yml does not work 

### ISSUE THREAD

**Issue by todoubaba** [grails/grails-core#614]
```yml
environments:
    development:
        dataSource:            
            dialect: ...
```

**Comment by todoubaba** [comment]
The workaround is setting it in grails-app/conf/hibernate properties.

**Comment by todoubaba** [comment]
The configClass in dataSource does not work too.

The workaround is setting them in hibernate section:

```yml
hibernate:
    config_class: ...
    dialect: ...
```
