### ISSUE TITLE
Grails 3.0.1 - Configuration unexpected behavior

### ISSUE THREAD

**Issue by yvdlima** [grails/grails-core#634]
The configuration doesn't generate Groovy maps if their key has any dots.

For example:
```
# application.yml
   test:
    configyml1: [ "key1.opt.uname": Spark, "key1.opt.pass": s2udIx9fdf9, "key1.opt2.lgroup": 2 ]
    configyml2:
        "path.to.exconfig": "/tmp/exconf.ini"
        "path.to.dbconfig": "/tmp/dbconfig"
# Will generate the following:
#     configyml1 -  Array of maps
# [[key1.opt.uname:Spark], [key1.opt.pass:s2udIx9fdf9], [key1.opt2.lgroup:2]]
#     configyml2 - Nested maps
# [path:[to:[exconfig:/tmp/exconf.ini, dbconfig:/tmp/dbconfig]]]
```
After reading the yaml documentation it's reasonable to generate those structures, but trying the Groovy version got these results.

```
application.groovy
test {
    configGroovy = ["groovy.map.m1":"val1", "groovy.map.m1":"val2", "groovy.map.m2":"val3"]
}
// configGroovy will be:
// [groovy:[map:[m1:val2, m2:val3]]]
```
I run trough this issue sending a email with the mail plugin for 3.0 version, which becomes quite hard to set up the props for smtp.
```
// From the docs 
grails {
   mail {
     host = "smtp.gmail.com"
     port = 465
     username = "youracount@gmail.com"
     password = "yourpassword"
     props = ["mail.smtp.auth":"true",
              "mail.smtp.socketFactory.port":"465",
              "mail.smtp.socketFactory.class":"javax.net.ssl.SSLSocketFactory",
              "mail.smtp.socketFactory.fallback":"false"]
   }
}
```
As a workaround I'm creating a plugin with purpose of loading before mail plugin and injecting the correct map structure.
```
   MyPluginGrailsPlugin.groovy
   //Ugly but works
   def loadBefore = ['services','mail']
    Closure doWithSpring() { {->            
            config = grailsApplication.getConfig()
            config.grails.mail.props = [
                "mail.smtp.auth": "true",
                "mail.smtp.socketFactory.port": "465",
                "mail.smtp.socketFactory.class": "javax.net.ssl.SSLSocketFactory",
                "mail.smtp.socketFactory.fallback": "false"
            ];
        }
    }
```
