### ISSUE TITLE
Grails 3.0.1 Missplaced hibernate propertities in application.yml file

### ISSUE THREAD

**Issue by GregorioBelinchonSaiz** [grails/grails-core#667]
It seems that the "hibernate" section that appears in "application.yml" file shouldn't be under "grails" section:

```
grails:
    mime:
        disable:
 .........
    hibernate:
        cache:
            queries: false
```

I think, "hibernate" section should be at the same level than grails.
I have created and empty Grails 3.0.1 project, then a domain class with "static mapping cache true" so L2 cache of hibernate is used. When I run the application "grails run-app" I get and exception with this cause:

Caused by: org.hibernate.cache.NoCacheRegionFactoryAvailableException: Second-level cache is used in the application, but property hibernate.cache.region.factory_class is not given; please either disable second level cache or set correct region factory using the hibernate.cache.region.factory_class setting and make sure the second level cache provider (hibernate-infinispan, e.g.) is available on the classpath.

Then, to fix the exception I need to put on the "application.yml" file next properties:

```
grails:
    mime:
        disable:
 .........
hibernate:
    cache:
        queries: false
        provider_class: net.sf.ehcache.hibernate.EhCacheProvider
        region:
            factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
```

But with "hibernate" at the same level than "grails", not under "grails" as it was when the project was initially created. Is this a bug in Grails 3.0.1?

Gregorio Belinchon
