### ISSUE TITLE
Cannot find template location

### ISSUE THREAD

**Issue by noamt** [grails/grails-core#9038]
I'm in the process of upgrading the JAX-RS plugin to Grails 3.0.2 ([new source](https://github.com/noamt/grails-jaxrs-plugin) and [build](https://travis-ci.org/noamt/grails-jaxrs-plugin)) and my integration tests keep hitting this exception:
```
Caused by: java.lang.IllegalStateException: Cannot find template location: classpath:/templates/ (please add some templates, check your Groovy configuration, or set spring.groovy.template.check-template-location=false)
```

even though the ``application.yml`` sets this option to ``false``:
```
spring:
    groovy:
        template:
            check-template-location: false
```

What am I missing?
