### ISSUE TITLE
Grails 3.0.2 built WAR not using correct environment

### ISSUE THREAD

**Issue by sergiodelamoshoptimix** [grails/grails-core#9043]
I am trying to deploy a Grails 3.0.2 app to a Tomcat 8 application Server hosted in Amazon AWS EC2 with a Postgresql database in RDS. I deploy the war with AWS Elastic Beanstalk. 

Before generating the war file in my build.gradle I replace 

     compile "org.springframework.boot:spring-boot-starter-tomcat"

with 

    provided "org.springframework.boot:spring-boot-starter-tomcat"

I generate the war with _grails prod war_
which greats me with: 

> BUILD SUCCESSFUL
>| Built application to build/libs using environment: **production**

The datasource part of my application.yml looks like

```yml
environments:
    development:
        grails:
            serverURL: http://localhost:8080
        dataSource:
            driverClassName: org.postgresql.Driver
            dialect: org.hibernate.dialect.PostgreSQLDialect
            dbCreate: none
            url: jdbc:postgresql://localhost:5432/db_dev
            username: test
            password: test
    test:
        grails:
            serverURL: http://localhost:8080
        dataSource:
            driverClassName: org.postgresql.Driver
            dialect: org.hibernate.dialect.PostgreSQLDialect
            dbCreate: none
            url: jdbc:postgresql://localhost:5432/db_test
            username: test
            password: test
    production:
        grails:
            serverURL: http://myapp.elasticbeanstalk.com
        dataSource:
            driverClassName: org.postgresql.Driver
            dialect: org.hibernate.dialect.PostgreSQLDialect
            dbCreate: none
            url: jdbc:postgresql://RDSURL:5432/RDS_DBNAME
            username: RDSMASTERUSER
            password: RDSMASTERPASSWORD
```

I upload  _build/libs/myapp-0.1.war_ but the application fails to connect to postgresql start. It is not using the production datasource configuration.

If I change the datasource part of my application.yml to use RDS credentials for every environment it works:

```yml
environments:
    development:
        grails:
            serverURL: http://localhost:8080
        dataSource:
            driverClassName: org.postgresql.Driver
            dialect: org.hibernate.dialect.PostgreSQLDialect
            dbCreate: none
            url: jdbc:postgresql://RDSURL:5432/RDS_DBNAME
            username: RDSMASTERUSER
            password: RDSMASTERPASSWORD
    test:
        grails:
            serverURL: http://localhost:8080
        dataSource:
            driverClassName: org.postgresql.Driver
            dialect: org.hibernate.dialect.PostgreSQLDialect
            dbCreate: none
            url: jdbc:postgresql://RDSURL:5432/RDS_DBNAME
            username: RDSMASTERUSER
            password: RDSMASTERPASSWORD
    production:
        grails:
            serverURL: http://myapp.elasticbeanstalk.com
        dataSource:
            driverClassName: org.postgresql.Driver
            dialect: org.hibernate.dialect.PostgreSQLDialect
            dbCreate: none
            url: jdbc:postgresql://RDSURL:5432/RDS_DBNAME
            username: RDSMASTERUSER
            password: RDSMASTERPASSWORD
```

Wit the above configuration. If I generate the war with _grails prod war_ and upload it, it works. 

Is it a bug? or am I missing something?
