### ISSUE TITLE
Grails 3.0.3.BUILD-SNAPSHOT: Placeholder in configuration is not resolved via Holders.config

### ISSUE THREAD

**Issue by nobeans** [grails/grails-core#9089]
Related to #9086 

```
# applicaiton.yml
environments:
    development:
        dataSource:
            dbCreate: create-drop
            url: '${JDBC_CONNECTION_STRING}'
```

```
// build.gradle
tasks.withType(org.springframework.boot.gradle.run.BootRunTask) {
    systemProperty('JDBC_CONNECTION_STRING', 'test')
}
```

It works well. But when I tried to get via `Holders.config`, it was still a expression of placeholder. Using the 3.0.2, both worked well.

* To reproduce:

```
# applicaiton.yml
testKey1: testValue1
testKey2: '${TEST_KEY2}'
```

```
// BootStrap.groovy
def init = {
    println grails.util.Holders.config.testKey1
    println grails.util.Holders.config.testKey2
}
```

```
// build.gradle
tasks.withType(org.springframework.boot.gradle.run.BootRunTask) {
    systemProperty('TEST_KEY2', 'test')
}
```

* Result:

3.0.2:
```
testValue1
test
```

Head of 3.0.3 (d380bea):
```
testValue1
${TEST_KEY2}
```
