### ISSUE TITLE
Environment specific properties cannot be overridden through an external property source in a Test.

### ISSUE THREAD

**Issue by kyleboon** [grails/grails-core#9116]
Here's some code demonstrating this:

```
class TestConfigController {

    def index() {
        def recipient = grailsApplication.config.getProperty('kylesKey')
        render "Hello ${recipient}"
    }
}
```

```
@TestFor(TestConfigController)
class TestConfigControllerSpec extends Specification {
    void "test something"() {
        when:
        controller.index()

        then:
        response.text == 'Hello SET-IN-TEST'
    }
}
```

Relevant portion of application.yml
```
environments:
    development:
        kylesKey: 'SET-IN-DEV'
     test:
        kylesKey: 'SET-IN-TEST'
```

This works correctly. If I try to override kylesKey in an external yaml file, I would expect my test to start to fail.

This loads a yaml config file from ~/test-server.yml
```
@ComponentScan("st.config")
class Application extends GrailsAutoConfiguration implements EnvironmentAware {
    static void main(String[] args) {
        GrailsApp.run(Application)
    }

    @Override
    void setEnvironment(Environment environment) {
        String configPath = System.getenv('GRAILS_CONFIG') ?: "${System.getProperty("user.home")}/test-server.yml"

        Resource resourceConfig = new FileSystemResource(configPath);
        YamlPropertiesFactoryBean ypfb = new YamlPropertiesFactoryBean();
        ypfb.setResources(resourceConfig);
        ypfb.afterPropertiesSet();
        Properties properties = ypfb.getObject();
        environment.propertySources.addFirst(new PropertiesPropertySource("ExternalConfig", properties))
    }
}
```

```
kylesKey: 'SET-IN-OVERRIDE'
onlyInOverride: 'onlyInOverride'

environments:
    development:
      kylesKey: 'SET-IN-OVERRIDE-ENV-SECTION-DEV'
    test:
      kylesKey: 'SET-IN-OVERRIDE-ENV-SECTION-TEST'
```

I wold expect the test to fail with this config file.

If I set a break point in EnvironmentAwarePropertySource.getProperty I can see that the list of property sources does not include ExternalConfig that was added in  Application.setEnvrionment.
