### ISSUE TITLE
Grails 3.0.8: grails.gorm.default.mapping.version ignored when set in application.yml

### ISSUE THREAD

**Issue by benorama** [grails/grails-core#9330]
I tried to set grails.gorm.default.mapping.version to false in application.yml.

```yml
grails:
    gorm:
        default:
            mapping:
                version: false
```

When running the app, the version property is still used in domain objects.
Is it still supported in Grails3?

Workaround: use version attribute in each domain mapping.
```groovy
    static mapping = {
        version false
    }
```
