### ISSUE TITLE
Grails 3.0.11 - naming_strategy is not working when using multiple datasources

### ISSUE THREAD

**Issue by urigon** [grails/grails-core#9565]
When using a single datasource, my custom naming strategy is applied.

But, if i use multiple datasources, it seems like my custom naming strategy is not applied.

**Comment by ctoestreich** [comment]
There was a change from previous grails where the name of the datasource would adhere to a naming format and use the portion of the name minus the `dataSource_` so that `dataSource_ocp` would simply become `ocp` when an underscore was in the name.  

In grails 3.x this seems to have changed and we simply just name them as `foo_bar` and use the whole word `foo_bar` in the domain class.

We have this working in 3.0.11 using the following:

``` yaml
dataSources:
    dataSource:
         url: 'jdbc:jtds:sqlserver://'
        username: xxxxxx
        password: xxxxx
        driverClassName: net.sourceforge.jtds.jdbc.Driver
        dialect: org.hibernate.dialect.SQLServerDialect
        pooled: true
        jmxExport: true
        logSql: false
        dbCreate: none
        properties:
            jmxEnabled: true
            initialSize: 5
            maxActive: 50
            minIdle: 5
            maxIdle: 25
            maxWait: 10000
            maxAge: 600000
            timeBetweenEvictionRunsMillis: 60000
            minEvictableIdleTimeMillis: 120000
            validationQuery: SELECT 1
            validationQueryTimeout: 3
            validationInterval: 15000
            testOnBorrow: true
            testWhileIdle: true
            testOnReturn: false
            jdbcInterceptors: ConnectionState
            defaultTransactionIsolation: 2
    ocp_content:
        url: 'jdbc:jtds:sqlserver://xxxxxxxxxx'
        username: xxxxxx
        password: xxxxx
        driverClassName: net.sourceforge.jtds.jdbc.Driver
        dialect: org.hibernate.dialect.SQLServerDialect
        pooled: true
        jmxExport: true
        logSql: false
        dbCreate: none
        properties:
            jmxEnabled: true
            initialSize: 5
            maxActive: 50
            minIdle: 5
            maxIdle: 25
            maxWait: 10000
            maxAge: 600000
            timeBetweenEvictionRunsMillis: 60000
            minEvictableIdleTimeMillis: 120000
            validationQuery: SELECT 1
            validationQueryTimeout: 3
            validationInterval: 15000
            testOnBorrow: true
            testWhileIdle: true
            testOnReturn: false
            jdbcInterceptors: ConnectionState
            defaultTransactionIsolation: 2
```

And then in the Domain class use something like this:

```groovy
class Site implements Serializable {

    String name
    ....

    static mapping = {
        table 'SITE'
        id column: 'SITE_ID'
        datasource 'ocp_content'
        ....
    }
}
```


If this doesn't work, could you please elaborate on your usage of datasources with code.

**Comment by ctoestreich** [comment]
We actually have 4 or 5 of these datasources in our application and they all work.  I simplified it to just the one to save on example code.

**Comment by urigon** [comment]
Thanks for replying. I guess my reporting was confusing.

Using multiple datasources is working ok, but specifying a custom naming strategy to multiple datasources seems not working correctly.

I have following grails-app/conf/application.yml.

```yaml
---
hibernate:
    naming_strategy: 'mydomain.MyCustomNamingStrategy'
    cache:
        queries: false
....
dataSources:
    dataSource:
        pooled: true
        ...
    sqlserver:
        pooled: true
        ...
```

And domain class is:

```groovy
class Product{
    Integer id
    String publisherName

    static mapping = {
        version false
        datasource 'product'
    }
}
```

In my "mydomain.MyCustomNamingStrategy", I'm capitalizing publisherName to PublisherName.

When I declare only one datasource as follows, it works fine.

```yaml
---
hibernate:
    naming_strategy: 'mydomain.MyCustomNamingStrategy'
    cache:
        queries: false
....
dataSource:
    pooled: true
```

```groovy
class Product{
    Integer id
    String publisherName

    static mapping = {
        version false
    }
}
```

**Comment by dariopardo** [comment]
I am also currently migrating to grails 3 and this is the last roadblock that I need to solve in order to be able to make the switch. The reason why I say so is because I just ran my application and all my tables got created again without my custom naming strategy (a prefix to the table name).Fortunately, I have done it in a sandbox environment and its fairly easy to drop the unwanted tables. However, it is a feature that we use in our plugins and grails apps to logically group tables by module (business owner, department, etc...). 

1. Is this something that is going to be fixed? 

2. or should we put the actual table name in the static mapping of all of our domains?

**Comment by mjcmatrix** [comment]
If you do not already have this in your config, can you try adding this to your `application.yml` (or `application.groovy`) config, next to your `hibernate` block; and see if it helps?

```
hibernate_sqlserver:
    naming_strategy: mydomain.MyCustomNamingStrategy
```
or for `application.groovy`:
```
hibernate_sqlserver {
	naming_strategy = mydomain.MyCustomNamingStrategy
}
```
The logic is that the `hibernate` config only applies to the default DataSource.

**Comment by dariopardo** [comment]
Hi @mjcmatrix ,

Thanks for your reply. I did have the following already in my application.yml:

`hibernate_sqlserver:
    naming_strategy: mydomain.MyCustomNamingStrategy`

This may work for you if only have one data source but if you have multiple it does not work. So in my scenario I have a plugin that uses a custom data source to prefix certain tables that that plugin is responsible for. Then In my application that uses that plugin I also have a custom naming strategy to separate certain data models based on business user/department like this:

Note: I am aware as well that in grails 3.0 they dropped dataSource_lookup dsl for just lookup. So I have accounted for that as well.

`class CustomNamingStrategy extends DefaultNamingStrategy {
	
	String classToTableName(String className) {
		 
		def packageName
		def prefix = ""
		def config
		
		//All domain class names need to be unique across packages in the application for this to work.
		Class clazz = Holders.grailsApplication.domainClasses.find { it.clazz.simpleName == className }.clazz
		packageName = clazz.getPackage().getName()
				
		if (packageName == 'recordretention'){
			config = Holders.config.dataSource.tablePrefixRecordRetention
			prefix = config
		}else if(packageName == 'foodordering'){
			config = Holders.config.dataSource.tablePrefixFoodOrdering
			prefix = config		
		}else if(packageName == 'vendorcustom'){
			config = Holders.config.dataSource_mySecondary.tablePrefixVendorCustom
			prefix = config
		}
		className = prefix + className		
        return covertFromCamelCase(super.classToTableName(className))
    }
	
	String propertyToColumnName(String propertyName) {
		return covertFromCamelCase(super.propertyToColumnName(propertyName))
	}

    private String covertFromCamelCase(String input) {
       
        GrailsNameUtils.getNaturalName(input).replaceAll("\\s", "_").toUpperCase();
    }

}
`
When I run my application under my current version 2.3.11 all my domains get mapped appropriately to the correct dataSource as well as the right prefixes get generated to the tables based on the package that they are under. But in grails 3.0 when I ran my app in development I have noticed that all my domains that are in my plugin got generated again without the prefix.

So meanwhile, to resolve it i have added the following to the static mapping of all my domains

`table 'MYPREFIX_TABLENAME`

I see that Graeme tag this so looks like it may get fixed soon.

Thanks

**Comment by urigon** [comment]
Hi, mjcmatrix.

Thank you for replying.

In my case, configuring application.yml as follows, my custom naming_strategy works as I expected.

```yaml
---
hibernate:
    cache:
        queries: false

hibernate_sqlserver:
    naming_strategy: 'mydomain.MyCustomNamingStrategy'
    cache:
        queries: false
```

So, my problem is solved. Should I leave this issue as opened until dariopardo's problem is resolved?

**Comment by graemerocher** [comment]
Looking at the code I don't see how @mjcmatrix's solution does not work for @dariopardo maybe you can elaborate, do you want it to default to the setting that is specified by `hibernate.naming_strategy` if a specific one is not specified such as `hibernate_sqlserver.naming_strategy`?

**Comment by dariopardo** [comment]
So I have put **hibernate_sqlserver** as suggested and I still ended up with duplicate tables without the custom naming strategy.  In my grails 2.3.11 application I did not have to add 2 hibernate blocks like below. How do I tell one datasource to use **hibernate:**  and  mySecondary to use **hibernate_sqlserver:**
```
hibernate:
    cache:
        queries: false
        use_second_level_cache: true
        region.factory_class: 'org.hibernate.cache.ehcache.EhCacheRegionFactory'
        naming_strategy: 'custom.CustomNamingStrategy'

hibernate_sqlserver:
    cache:
        queries: false
        use_second_level_cache: true
        region.factory_class: 'org.hibernate.cache.ehcache.EhCacheRegionFactory'
        naming_strategy: 'custom.CustomNamingStrategy'

endpoints:
    jmx:
        unique-names: true

dataSources:
    dataSource:
        pooled: true
        jmxExport: true
        dialect: org.hibernate.dialect.SQLServerDialect
        driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
        username: myUserName
        password: myPassword
        tablePrefixInfiniteCampusCustom: 'Ccs'
        configClass: 'iccustom.DomainConfiguration'
    mySecondary:
            pooled: true
            jmxExport: true
            dialect: org.hibernate.dialect.SQLServerDialect
            driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
            username: myUserName
            password: myPassword

            tablePrefixInfiniteCampusCustom: Ccs
            configClass: 'iccustom.DomainConfiguration'
```


I think I am just going to map the table names.
