### ISSUE TITLE
GORM5 + Spring Boot ignores ddl-auto hibernate directives (and injects foreign keys in any way)

### ISSUE THREAD

**Issue by mvniekerk** [grails/grails-core#9641]
I don't want Hibernate to recreate or update the database schema.

According to the documentation, you need to have this in your application.yml file:
spring.jpa.hibernate.ddl-auto: none

It doesn't work.

Here's my application.yml file:

```
spring:
  profiles.active: default

spring.jpa.hibernate.ddl-auto: none
---
spring:
  profiles: default

spring.datasource:
    driverClassName: net.sourceforge.jtds.jdbc.Driver
    url: jdbc:jtds:sqlserver://IP/DB
    username: user
    password: password
spring.jpa:
    hibernate:
        ddlAuto: validate
    showSql: true
hibernate:
        ddl-auto: none
---
spring:
   profiles: unit-test

spring.datasource:
    pooled: true
    jmxExport: true
    driverClassName: org.h2.Driver
    username: sa
    password:
    dbCreate: create-drop
    url: jdbc:h2:mem:devDb;MVCC=FALSE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=TRUE

```

Documentation link:

https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html

Note I've also changed ddl-auto with ddlAuto, still doesn't work.

build.gradle:

```
buildscript {
    repositories {
        mavenCentral()
        jcenter()
        maven { url "https://repo.spring.io/libs-release" }
    }
    dependencies {
        classpath 'com.github.jengelman.gradle.plugins:shadow:1.2.2'
        classpath "org.springframework.boot:spring-boot-gradle-plugin:1.3.+"
    }
}

repositories {
    mavenCentral()
    mavenLocal()
    jcenter()
}

apply plugin: 'spring-boot'

dependencies {
 //Spring
                compile "org.springframework.boot:spring-boot-configuration-processor"
                compile "org.springframework.boot:spring-boot-starter"
                compile "org.grails:gorm-hibernate4-spring-boot:5.0.+"
                compile 'javax.el:javax.el-api:2.2.5'

                //DB
                testCompile 'com.h2database:h2:1.4.190'
                compile 'net.sourceforge.jtds:jtds:1.3.1'
                compile 'commons-dbcp:commons-dbcp:1.4'
}

```
