### ISSUE TITLE
Grails3 custom naming_strategy does not apply through associations

### ISSUE THREAD

**Issue by kktec** [grails/grails-core#9662]
When working with Grails 3.1.1 (java8 & Windows):

I have 2 domain classes, Domain and DomainForm. DomainForm has a dependency on Domain (FK).

The problem seems to be in conjunction with a Hibernate naming_strategy, org.hibernate.cfg.DefaultNamingStrategy, that implements CamelCase db artifact names rather than the standard snake_case.

**In application.yml:**
```
hibernate:
    naming_strategy: org.hibernate.cfg.DefaultNamingStrategy
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: false
        region.factory_class: 'org.hibernate.cache.ehcache.EhCacheRegionFactory'
    format_sql: true
    dialect: org.hibernate.dialect.SQLServer2008Dialect


```
**The Domain class look like this:**
```
class Domain {
	
	Integer id
	
	static mapping = {
		table 'Domain'
		id column: 'domainId'
	}
}

```
**The DomainForm class looks like this:**
```
class DomainForm extends Auditable3 {
		
	Integer id
	
	Domain domain
	Integer domainFormTypeId
	
	String formDetailsXml
	
	static mapping = {
		table 'DomainForm'
		id column: 'domainFormId'
	}
}

```
**When I try to save a new DomainForm referencing an existing Domain, the SQL generated by Hibernate looks like this:**
```
    select
        domain0_.domainId as domainId1_0_0_,
        domain0_.version as version2_0_0_,
        domain0_.displayName as displayN3_0_0_,
        domain0_.domainName as domainNa4_0_0_ 
    from
        Domain domain0_ 
    where
        domain0_.domainId=?
 
    insert 
    into
        DomainForm
        (version, createdBy, dateCreated, dateDeleted, deletedBy, domain_id, domainFormTypeId, formDetailsXml, lastUpdated, lastUpdatedBy) 
    values
        (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)

```

**Resulting in:**
```
ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper - Invalid column name 'domain_id'.
ERROR grails.app.controllers.com.lemans.correspondence.forms.DomainFormController - org.springframework.jdbc.BadSqlGrammarException: Hibernate operation: could not execute statement; bad SQL grammar [n/a]; nested exception is java.sql.SQLException: Invalid column name 'domain_id'.

```

**The invalid column for the Domain foreign key reference should of course be named domainId, not domain_id.**

Naive attempts to workaround by adding to the mapping block did not work:
```
		domain_id column: 'domainId'
		domainId column: 'domain_id'

```		
We have used this naming_strategy on our Grails 2.4 apps without this problem.
