### ISSUE TITLE
3.1.1 : OPTIONS method not being passed to interceptors; unable to set spring.mvc.dispatchTraceRequest and spring.mvc.dispatchOptionsRequest

### ISSUE THREAD

**Issue by orubel** [grails/grails-core#9784]
According to Springboot documentation (https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html) , I should be able to set the following variables in application.yml or application.groovy.

Here is what I have in my YML that is failing:

```
spring:
    groovy:
        template:
            check-template-location: false
    mvc:
        dispatch-trace-request: true
        dispatch-options-request: true
```

See http://stackoverflow.com/questions/33331042/how-to-handle-http-options-requests-in-spring-boot

just added 'mvc.dispatch-trace-request' and 'mvc.dispatch-options-request' and both are causing that error.

These are throwing the following error:

`java.lang.IllegalStateException: Initialization parameters can not be set after the context has been initialized`

Spring and Springboot say to do this as well ( https://jira.spring.io/browse/SPR-10093?jql=text%20~%20%22dispatch-options-request%22 )

Past versions of Grails said to do this(https://jira.grails.org/browse/GRAILS-5531) in web.xml and past versions of CORS did similar things.

Currently, without these settings, we are blocked from using OPTIONS and TRACE.

What is suggested way for setting these variables or getting these options set?

**Comment by orubel** [comment]
BTW, you will have to set it as follows in application.groovy:

```
spring.mvc.dispatchTraceRequest=false
spring.mvc.dispatchOptionsRequest=false
```

The dashes are not acceptable (bad documentation I assume)

**Comment by orubel** [comment]
Here is what I have in my YML that is failing:

```
spring:
    groovy:
        template:
            check-template-location: false
    mvc:
        dispatch-trace-request: false
        dispatch-options-request: false
```

just added 'mvc.dispatch-trace-request' and 'mvc.dispatch-options-request' and both are causing that error.
