### ISSUE TITLE
server.contextPath is not working if used at root and as well as under environments key.

### ISSUE THREAD

**Issue by ManvendraSK** [grails/grails-core#9916]
### Task List

- [ ] Steps to reproduce provided
- [ ] Full description of the issue provided (see below)

### Steps to Reproduce

1. I added server.contextPath to **application.yml**.
```yml
server:
    contextPath : '/myApp'

environments:
    development:
        dataSource:
            dbCreate: create-drop
            url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
        server:
            contextPath : '/myAppDev'

    test:
        dataSource:
            dbCreate: update
            url: jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
```

### Expected Behaviour

App should now listen for the url **http://localhost:8080/myAppDev**, which indeed is. But upon hitting the url, it's throwing **404**. 
### Actual Behaviour

If I go to **http://localhost:8080/myApp** then it's working fine. 

### Debug info

I removed the root server.contextPath, then it worked for **/myAppDev**. If I'm providing both simultaneously, then it's not working. I would like to know, if this top level context path supposed to be removed if we are specifying it inside environments key.

### Environment Information

- **Operating System**: Fedora 22, Linux
- **Grails Version:** 3.1.4
- **JDK Version:** 1.7.0_51, Java HotSpot 64-bit
- **Container Version (If Applicable):** **none**
