### ISSUE TITLE
Add scripting feature (Refreshable Beans) to Grails 3.x

### ISSUE THREAD

**Issue by forseti** [grails/grails-core#9925]
This ticket is about the Refreshable Beans feature from Spring: (http://docs.spring.io/autorepo/docs/spring/3.2.x/spring-framework-reference/html/dynamic-language.html)

Although this feature can be enabled through resources.groovy, it would be great if Grails 3.x support this out of the box.

For example 

inside application.yml, we can configure the behaviour:

```
    scriptFactoryPostProcessor:
        lang: 'groovy'
        defaultRefreshCheckDelay: 2000
        locations: [ '/home/user/appName/scripts' ]
```

Any script located under '/home/user/appName/scripts' will be added into Spring container.

Thanks!

Donny
